// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnikiMBussiness.Models;

namespace OnikiMBussiness.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20200312141937_sp-Stok")]
    partial class spStok
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnikiMBussiness.Models.Sti", b =>
                {
                    b.Property<string>("EvrakNo")
                        .HasColumnType("varchar(16)")
                        .HasMaxLength(16)
                        .IsUnicode(false);

                    b.Property<int>("Tarih")
                        .HasColumnType("int");

                    b.Property<short>("IslemTur")
                        .HasColumnType("smallint");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("varchar(4)")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("numeric(25, 6)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MalKodu")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric(25, 6)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric(25, 6)");

                    b.HasKey("EvrakNo", "Tarih", "IslemTur")
                        .HasName("pkSTI");

                    b.ToTable("STI");
                });

            modelBuilder.Entity("OnikiMBussiness.Models.Stk", b =>
                {
                    b.Property<string>("MalKodu")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MalAdi")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("MalKodu")
                        .HasName("pkSTK");

                    b.ToTable("STK");
                });
#pragma warning restore 612, 618
        }
    }
}
